### ISSUE TITLE
Install error when i install it

### ISSUE THREAD

**Issue by maxiang0305** [RongLiu-Leo/Gaussian-Splatting-Monitor#10]
when I run the commend "cmake --build build -j24 --target install"
I got this:
<details><summary>Details</summary>
<p>
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/projects/remote/apps/remoteGaussianUI/CMakeFiles/SIBR_remoteGaussian_app.dir/build.make:188: src/projects/remote/apps/remoteGaussianUI/SIBR_remoteGaussian_app] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1519: src/projects/remote/apps/remoteGaussianUI/CMakeFiles/SIBR_remoteGaussian_app.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
/usr/bin/ld: /lib/libgdal.so.30: undefined reference to `std::condition_variable::wait(std::unique_lock<std::mutex>&)@GLIBCXX_3.4.30'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/projects/basic/apps/pointBased/CMakeFiles/SIBR_PointBased_app.dir/build.make:187: src/projects/basic/apps/pointBased/SIBR_PointBased_app] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1336: src/projects/basic/apps/pointBased/CMakeFiles/SIBR_PointBased_app.dir/all] Error 2
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/projects/basic/apps/texturedMesh/CMakeFiles/SIBR_texturedMesh_app.dir/build.make:187: src/projects/basic/apps/texturedMesh/SIBR_texturedMesh_app] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1247: src/projects/basic/apps/texturedMesh/CMakeFiles/SIBR_texturedMesh_app.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
</p>
</details> 
Do you have some idea?

**Comment by RongLiu-Leo** [comment]
What's your OS?

**Comment by maxiang0305** [comment]
> What's your OS?

unbuntu22.04
Thank you for your reply, I have found the way to solve this bug.

**Comment by RongLiu-Leo** [comment]
Cool.
Please let me know if you use the monitor for your project so I can add your repo into the README to enrich the application gallery.👏

**Comment by QZH-00** [comment]
May I ask how you solved it? Any references?
Thanks !

**Comment by kunyuwan** [comment]
> > What's your OS?
> 
> unbuntu22.04 Thank you for your reply, I have found the way to solve this bug.

Please tell me how to solve it, I also encountered the same problem

**Comment by maxiang0305** [comment]
> May I ask how you solved it? Any references? Thanks !



> > > What's your OS?
> > 
> > 
> > unbuntu22.04 Thank you for your reply, I have found the way to solve this bug.
> 
> Please tell me how to solve it, I also encountered the same problem


I found that the issue with this bug was that the compiler incorrectly linked to the Anaconda libraries. Therefore, the best solution is to modify the environment variables before compiling. To do this, I ran the following commands:
`export PATH=/usr/local/bin:/usr/bin:/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib`

**Comment by maxiang0305** [comment]
> > > What's your OS?
> > 
> > 
> > unbuntu22.04 Thank you for your reply, I have found the way to solve this bug.
> 
> Please tell me how to solve it, I also encountered the same problem



> May I ask how you solved it? Any references? Thanks !


I found that the issue with this bug was that the compiler incorrectly linked to the Anaconda libraries. Therefore, the best solution is to modify the environment variables before compiling. To do this, I ran the following commands:
```
export PATH=/usr/local/bin:/usr/bin:/bin:$PATH
export LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib
```
