### ISSUE TITLE
How to rotate the model around the x, y, and z axes~

### ISSUE THREAD

**Issue by kimwao** [RongLiu-Leo/Gaussian-Splatting-Monitor#12]
Thank you for providing great convenience with your work！At present, I can only control the left and right mouse buttons to move up, down, left and right. How can Windows perform rotation operations, especially around the axis.
The red ellipse in your demonstration video did not appear in my “point view”, but instead appeared in my “top view”. I don't know how to adjust it.
Looking forward to your reply, thank you very much

**Comment by RongLiu-Leo** [comment]
Try to switch the FPS control mode to Trackball

**Comment by kimwao** [comment]
It’s work! Thank you!
