### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by danperazzo** [RongLiu-Leo/Gaussian-Splatting-Monitor#6]
Hello, thanks for the amazing project! I was trying to use this viewer to visualize the gaussians on 2dgs but the viewer is not showing me anything, Is there anything you would recomend?

**Comment by RongLiu-Leo** [comment]
See the corresponding branch:
[https://github.com/RongLiu-Leo/2d-gaussian-splatting](https://github.com/RongLiu-Leo/2d-gaussian-splatting)
