### ISSUE TITLE
No sudo access

### ISSUE THREAD

**Issue by branyang02** [RongLiu-Leo/Gaussian-Splatting-Monitor#7]
Thanks for the amazing project! 

I was wondering if it is possible to install this in an environment without sudo access. In addition, I am also wondering if the Linux environment is restricted to Ubuntu 22.04.

Thanks!

**Comment by RongLiu-Leo** [comment]
Yes, the Linux environment is restricted to Ubuntu 22.04.

The sudo line is used to install some dependencies for compilation. It could be ignored if you have already installed these dependencies or if you find other ways to install them.
